version: '3'
services:
  flask:
    build: .
    # ports:
    #   - "5000:5000"

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    depends_on:
      - flask